= Parameters

The parent key for all of the following parameters is `paralus`.

== `namespace`

[horizontal]
type:: string
default:: `syn-paralus`

The namespace in which to deploy Paralus ZTKA

== `charts`

[horizontal]
type:: object
default:: See https://github.com/projectsyn/component-paralus/blob/master/class/defaults.yml[`class/defaults.yml`]

Helm charts used by the component.

== `images`

[horizontal]
type:: object
default:: See https://github.com/projectsyn/component-paralus/blob/master/class/defaults.yml[`class/defaults.yml`]

Container images used by the component.

The component will rewrite references to `busybox:latest` with the Busybox image specified in this parameter.

[NOTE]
====
Currently, the Paralus images aren't referenced here.
If you want to customize the Paralus images, please do so directly in parameter `helm_values`.
====

== `dashboard_container_port`

[horizontal]
type:: integer
default:: `8000`

The container port to use for the Paralus dashboard.

The component will generate a custom nginx configuration and will patch the dashboard deployment generated by the Helm chart to ensure that the nginx process in the dashboard container listens on the port specified here.

[NOTE]
====
The dashboard deployment currently isn't configurable in the Helm chart.
If the Helm chart ever gains support for customizing the dashboard deployment, the implementation for this parameter should be reevaluated.
====

== `helm_values`

[horizontal]
type:: object
default:: See https://github.com/projectsyn/component-paralus/blob/master/class/defaults.yml[`class/defaults.yml`]

The Helm values for the Paralus ZTKA Helm chart.

See the https://github.com/paralus/helm-charts/blob/main/charts/ztka/values.yaml[upstream default values] for supported values

[NOTE]
====
The component applies a significant amount of post-processing to the rendered Paralus ZTKA helm chart.
Primarily, the post-processing enables the Paralus ZTKA components to run in a restricted environment, such as OpenShift 4.
====
